const {
  GoogleGenerativeAI,
  HarmCategory,
  HarmBlockThreshold,
} = require("@google/generative-ai");

let genAI = null;
let model = null;

/**
 * Initialize the Gemini API client
 * @param {string} apiKey - The Gemini API key
 */
function initialize(apiKey) {
  if (!apiKey) {
    throw new Error("Gemini API key is required");
  }

  try {
    genAI = new GoogleGenerativeAI(apiKey);
    // Using gemini-pro model as it's best suited for text-only inputs
    model = genAI.getGenerativeModel({
      model: "gemini-2.5-flash",
      // Add safety settings as per official docs
      safetySettings: [
        {
          category: HarmCategory.HARM_CATEGORY_HARASSMENT,
          threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
        },
        {
          category: HarmCategory.HARM_CATEGORY_HATE_SPEECH,
          threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
        },
        {
          category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
          threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
        },
        {
          category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
          threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
        },
      ],
    });
    console.log("Gemini AI service initialized successfully");
  } catch (error) {
    console.error("Failed to initialize Gemini AI service:", error);
    throw new Error("Failed to initialize Gemini AI service");
  }
}

/**
 * Construct the prompt for Gemini API based on quiz parameters
 * @param {string} category - Category of the quiz (Book or Topic)
 * @param {string} topicName - Topic Name or Book Title
 * @param {string} topicDescription - Optional requirements for the topic
 * @param {number} numberOfQuestions - Number of questions to generate
 * @param {string} difficulty - Difficulty level
 * @returns {string} - Constructed prompt
 */
function constructPrompt(
  category,
  topicName,
  topicDescription,
  numberOfQuestions,
  difficulty
) {
  let subject = category === "Book" ? "the book" : "the topic";
  if (topicName) {
    subject += ` "${topicName}"`;
  } else {
    subject += ` in the ${category} category`;
  }

  // Special instruction for book quizzes to avoid title repetition
  let bookInstruction = "";
  if (category === "Book") {
    bookInstruction =
      "\n\nIMPORTANT: For book quizzes, do not repeat the book title in every question. Focus on the content, storyline, characters, and themes instead.";
  }

  let additionalContext = "";
  if (topicDescription && topicDescription.trim()) {
    additionalContext = `\n\nAdditional requirements: ${topicDescription.trim()}`;
  }

  console.log("numberOfQuestions: ", numberOfQuestions);

  return `Generate EXACTLY ${numberOfQuestions} multiple-choice quiz questions about ${subject} with ${difficulty} difficulty level. It is CRITICAL that you generate the exact number of questions requested - no more, no less.${additionalContext}${bookInstruction}

For each question, provide:
1. The question text
2. Four options (A, B, C, D)
3. The correct answer (indicate which option is correct)
4. A brief explanation for the correct answer

Format each question STRICTLY as follows:

QUESTION: [Question text]
OPTIONS:
A. [Option A]
B. [Option B]
C. [Option C]
D. [Option D]
CORRECT_ANSWER: [Correct option letter]
EXPLANATION: [Brief explanation]

Ensure the questions are factually accurate, clear, and appropriate for the ${difficulty} difficulty level.

IMPORTANT: You MUST generate EXACTLY ${numberOfQuestions} questions following this format. Each question MUST have exactly 4 options labeled A, B, C, and D. Each question MUST have a clear correct answer and explanation.`;
}

/**
 * Parse the generated content into quiz questions
 * @param {string} generatedText - Text generated by Gemini API
 * @param {number} timePerQuestion - Time per question in seconds
 * @returns {Array} - Array of parsed questions
 */
function parseGeneratedQuestions(generatedText, timePerQuestion) {
  const questions = [];
  console.log("Raw generated text length:", generatedText.length);
  console.log(
    "Raw generated text sample:",
    generatedText.substring(0, 200) + "..."
  );

  // Improved regex pattern to better identify question blocks
  const questionBlocks = generatedText
    .split(/(?:^|\n\n)QUESTION:/)
    .filter((block) => block.trim());

  console.log("Number of question blocks identified:", questionBlocks.length);

  for (let i = 0; i < questionBlocks.length; i++) {
    const block = questionBlocks[i];
    console.log(
      `Processing question block ${i + 1}/${questionBlocks.length}, length: ${
        block.length
      }`
    );

    try {
      // Extract question components using regex
      const questionMatch = block.match(/(.+?)\s*(?:OPTIONS:|\n\n)/s);
      const optionsMatch = block.match(
        /OPTIONS:\s*([\s\S]*?)(?:CORRECT_ANSWER:|\n\n)/s
      );
      const correctAnswerMatch = block.match(/CORRECT_ANSWER:\s*([A-D])/i);
      const explanationMatch = block.match(
        /EXPLANATION:\s*([\s\S]*?)(?:\n\n|$)/s
      );

      if (!questionMatch || !optionsMatch || !correctAnswerMatch) {
        console.warn("Skipping malformed question block:", block);
        continue;
      }

      const questionText = questionMatch[1].trim();
      const optionsText = optionsMatch[1].trim();
      const correctAnswer = correctAnswerMatch[1].trim();
      const explanation = explanationMatch ? explanationMatch[1].trim() : "";

      console.log(
        `Question ${i + 1} text: ${questionText.substring(0, 50)}...`
      );
      console.log(
        `Question ${i + 1} options text length: ${optionsText.length}`
      );
      console.log(`Question ${i + 1} correct answer: ${correctAnswer}`);

      // Parse options with improved regex
      const options = [];
      const optionRegex = /([A-D])\.\s*(.+?)(?=\n[A-D]\.|$)/gs;
      let optionMatch;

      while ((optionMatch = optionRegex.exec(optionsText)) !== null) {
        const optionLetter = optionMatch[1].trim();
        const optionText = optionMatch[2].trim();
        options.push({
          text: optionText,
          isCorrect: optionLetter === correctAnswer,
        });
      }

      console.log(`Question ${i + 1} parsed options count: ${options.length}`);

      // Ensure we have exactly 4 options
      if (options.length !== 4) {
        console.warn(
          `Question has ${options.length} options instead of 4, attempting to fix:`,
          questionText
        );

        // Try alternative parsing approach for options
        const optionLines = optionsText
          .split("\n")
          .filter((line) => line.trim());
        if (optionLines.length >= 4) {
          options.length = 0; // Clear existing options
          for (let j = 0; j < 4; j++) {
            if (j < optionLines.length) {
              const line = optionLines[j];
              const match = line.match(/^([A-D])\.\s*(.+)$/i);
              if (match) {
                const optionLetter = match[1].trim();
                const optionText = match[2].trim();
                options.push({
                  text: optionText,
                  isCorrect: optionLetter === correctAnswer,
                });
              }
            }
          }
          console.log(
            `Question ${i + 1} options after fix attempt: ${options.length}`
          );
        }

        // If still not 4 options, skip this question
        if (options.length !== 4) {
          console.warn(
            `Still unable to parse 4 options, skipping question ${i + 1}`
          );
          continue;
        }
      }

      // Create question object
      questions.push({
        text: questionText,
        options: options,
        explanation: explanation,
        timeLimit: timePerQuestion,
      });
      console.log(`Successfully added question ${i + 1} to the quiz`);
    } catch (error) {
      console.error(`Error parsing question block ${i + 1}:`, error);
    }
  }

  console.log(`Total questions successfully parsed: ${questions.length}`);

  return questions;
}

/**
 * Generate quiz questions based on the provided parameters
 * @param {Object} quizParams - Parameters for generating quiz questions
 * @param {string} quizParams.category - Category of the quiz (Book or Topic)
 * @param {string} quizParams.topicName - Topic Name or Book Title
 * @param {string} quizParams.topicDescription - Optional requirements for the topic
 * @param {number} quizParams.numberOfQuestions - Number of questions to generate
 * @param {string} quizParams.difficulty - Difficulty level (easy, medium, hard)
 * @param {number} quizParams.timePerQuestion - Time per question in seconds
 * @returns {Promise<Array>} - Array of generated questions
 */
async function generateQuizQuestions(quizParams) {
  if (!model) {
    throw new Error("Gemini AI service not initialized");
  }

  console.log("Quiz parameters received:", JSON.stringify(quizParams, null, 2));
  console.log(`Requested number of questions: ${quizParams.numberOfQuestions}`);

  const {
    category,
    topicName,
    topicDescription,
    numberOfQuestions,
    difficulty,
    timePerQuestion,
  } = quizParams;

  try {
    // Configure generation parameters as per official docs
    const generationConfig = {
      temperature: 0.7,
      topK: 40,
      topP: 0.8,
      maxOutputTokens: 4096, // Increased token limit to ensure we get enough content for all questions
    };

    console.log("Using generation config:", generationConfig);

    // Start a chat to maintain context
    const chat = model.startChat({
      generationConfig,
      history: [],
    });

    // Construct the prompt for Gemini API
    const prompt = constructPrompt(
      category,
      topicName,
      topicDescription,
      numberOfQuestions,
      difficulty
    );

    console.log("Generated prompt for AI:", prompt);

    // Generate content using Gemini API with streaming disabled for quiz generation
    console.log("Sending request to Gemini API...");
    const result = await chat.sendMessage(prompt);
    const response = await result.response;
    const text = response.text();

    console.log("Received response from Gemini API, text length:", text.length);
    console.log("Response sample:", text.substring(0, 100) + "...");

    // Parse the generated content into quiz questions
    const parsedQuestions = parseGeneratedQuestions(text, timePerQuestion);
    console.log(
      `Final number of questions after parsing: ${parsedQuestions.length}`
    );

    return parsedQuestions;
  } catch (error) {
    console.error("Error generating quiz questions:", error);
    if (error.response) {
      // Handle API-specific errors
      const { status, data } = error.response;
      throw new Error(
        `Failed to generate quiz questions: ${status} - ${
          data?.error?.message || "Unknown error"
        }`
      );
    }
    throw new Error("Failed to generate quiz questions");
  }
}

module.exports = {
  initialize,
  generateQuizQuestions,
};
